export const SET_TODO_LIST = 'SET_TODO_LIST';
export const DELETE_ROW = 'DELETE_ROW';
export const SET_SHOW_ADD_TODO_AREA = 'SET_SHOW_ADD_TODO_AREA';
export const SET_NEW_TODO_VALUE = 'SET_NEW_TODO_VALUE';
export const SUBMIT_NEW_TODO_VALUE = 'SUBMIT_NEW_TODO_VALUE';
export const SET_INCOMPLETE_ONLY = 'SET_INCOMPLETE_ONLY';
export const SET_EDITOR_ID_AND_VAL = 'SET_EDITOR_ID_AND_VAL';
export const SET_ROW_EDITOR_VAL = 'SET_ROW_EDITOR_VAL';
export const SUBMIT_ROW_EDITOR_VAL = 'SUBMIT_ROW_EDITOR_VAL';
export const COMPLETE_CHECKBOX_VAL = 'COMPLETE_CHECKBOX_VAL';

